version: "3.8"

services:
  veyltech-app:
    image: veyltech-app:latest
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    networks:
      - veyltech-network

networks:
  veyltech-network:
    driver: overlay
