version: "3.8"

services:
  veyltech-app:
    image: veyltech-app:latest
    ports:
      - "3002:3000"  # Dış:3002 ↔ İç:3000 (artık uyumlu)
    networks:
      - veyltech-network

networks:
  veyltech-network:
    driver: overlay